### ISSUE TITLE
velocity values consistency

### ISSUE THREAD

**Issue by jjYBdx4IL** [ekumanov/cybrid#4]
Hey there! Are you interested in checking out a method to check the consistency of velocity output values from your Cybrid and N1X and maybe some rubber contact based instrument? I have done some first tests, and the rubber contact based products seem to deliver pretty inconsistent results. I have written a simple VST plugin for Win64 to compute and display the velocity delta of two simultaneously pressed keys. I'm just not quite sure how the method of pressing two neighboring white keys at once itself is reliable. If your optical sensor devices show that it's pretty consistent, that would be very helpful. It would also show that optical sensors are a must have for serious players.

**Comment by ekumanov** [comment]
Hey, sorry for the late reply, I just saw this. Sounds interesting, but the problems is I don't have the Cybrid anymore with me, had to store it in another apartment since I don't have space for it at home :( I only keep the N1X but I can test it for consistency too. Cheers!

**Comment by ekumanov** [comment]
BTW, I created a piano forum where we can discuss things like that, feel free to join: https://pianoclack.com/forum/

**Comment by davidedelvento** [comment]
I'll be happy to contribute to this one too, I'm building something similar to the Cybrid and active on said forum.
