### ISSUE TITLE
Scanning speed and velocity mapping of Cybrid

### ISSUE THREAD

**Issue by davidedelvento** [ekumanov/cybrid#5]
Question: you mentioned a while back (I think it was on PW) that you needed an intense "mapping" to provide appropriate MIDI velocities from the measured times. Looking at your code a https://github.com/ekumanov/cybrid/blob/master/src/teensy/main/My_Hybrid_Piano_V1.2.ino#L220-L245 I think shows what you were talking about. I think I understand and can reverse engineer it, but I think a discussion is better. So the question is: how are you mapping from time to MIDI velocity, do you have a plot of the curve you are using with a range of parameter that you tried (and accepted or discarded) -- basically anything that is not already evident from the code section I linked and even anything that you'd like to add to explain about that code even if it's evident.

**Comment by ekumanov** [comment]
@davidedelvento, see my answer here: https://pianoclack.com/forum/d/289-scanning-speed-and-velocity-mapping-of-cybrid/2
